-- MySQL Script generated by MySQL Workbench
-- Thu Jun  6 21:29:10 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema petfind
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema petfind
-- -----------------------------------------------------


CREATE SCHEMA IF NOT EXISTS `petfind` DEFAULT CHARACTER SET utf8 ;
USE `petfind` ;

-- -----------------------------------------------------
-- Table `petfind`.`table1`
-- -----------------------------------------------------


-- -----------------------------------------------------
-- Table `petfind`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petfind`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(50) NOT NULL,
  `completeName` VARCHAR(45) NOT NULL,
  `pathUserImage` VARCHAR(100),
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `cep` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC) VISIBLE,
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petfind`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petfind`.`Post` (
  `idPost` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NULL,
  `imagesPath` VARCHAR(100) NOT NULL,
  `fkIdUser` INT NOT NULL,
  `localization` VARCHAR(100) NOT NULL,
  `publiType` VARCHAR(10) NOT NULL,
  `animalName` VARCHAR(45) NULL,
  `animalSpecie` VARCHAR(45) NOT NULL,
  `animalGender` VARCHAR(45) NOT NULL,
  `animalColor` VARCHAR(45) NOT NULL,
  `animalSize` VARCHAR(45) NOT NULL,
  `datePosted` DATETIME NOT NULL,
  PRIMARY KEY (`idPost`),
  UNIQUE INDEX `idPost_UNIQUE` (`idPost` ASC) VISIBLE,
  INDEX `fkUserId_idx` (`fkIdUser` ASC) VISIBLE,
  CONSTRAINT `fkIdUser_Post`
    FOREIGN KEY (`fkIdUser`)
    REFERENCES `petfind`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `petfind`.`Comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petfind`.`Comments` (
  `idComments` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(100) NOT NULL,
  `fkIdPost` INT NOT NULL,
  `fkIdUser` INT NOT NULL,
  PRIMARY KEY (`idComments`),
  UNIQUE INDEX `idComments_UNIQUE` (`idComments` ASC) VISIBLE,
  INDEX `fkIdPost_idx` (`fkIdPost` ASC) VISIBLE,
  INDEX `fkIdUser_idx` (`fkIdUser` ASC) VISIBLE,
  CONSTRAINT `fkIdPost_Comments`
    FOREIGN KEY (`fkIdPost`)
    REFERENCES `petfind`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkIdUser_Comments`
    FOREIGN KEY (`fkIdUser`)
    REFERENCES `petfind`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petfind`.`Reaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petfind`.`Reaction` (
  `idReaction` INT NOT NULL AUTO_INCREMENT,
  `fkIdUser` INT NOT NULL,
  `reactrionType` VARCHAR(45) NOT NULL,
  `fkIdPost` INT NOT NULL,
  PRIMARY KEY (`idReaction`),
  UNIQUE INDEX `idReaction_UNIQUE` (`idReaction` ASC) VISIBLE,
  INDEX `fkIdPost_idx` (`fkIdPost` ASC) VISIBLE,
  INDEX `fkIdUser_idx` (`fkIdUser` ASC) VISIBLE,
  CONSTRAINT `fkIdUser_Reaction`
    FOREIGN KEY (`fkIdUser`)
    REFERENCES `petfind`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkIdPost_Reaction`
    FOREIGN KEY (`fkIdPost`)
    REFERENCES `petfind`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



INSERT INTO `petfind`.`User` (`userName`, `completeName`, `pathUserImage`, `email`, `password`, `cep`)
VALUES
('user1', 'User One', '/images/user1.png', 'user1@example.com', 'pass1234', 12345),
('user2', 'User Two', '/images/user2.png', 'user2@example.com', 'pass1234', 12345),
('user3', 'User Three', '/images/user3.png', 'user3@example.com', 'pass1234', 12345),
('user4', 'User Four', '/images/user4.png', 'user4@example.com', 'pass1234', 12345),
('user5', 'User Five', '/images/user5.png', 'user5@example.com', 'pass1234', 12345),
('user6', 'User Six', '/images/user6.png', 'user6@example.com', 'pass1234', 12345),
('user7', 'User Seven', '/images/user7.png', 'user7@example.com', 'pass1234', 12345),
('user8', 'User Eight', '/images/user8.png', 'user8@example.com', 'pass1234', 12345),
('user9', 'User Nine', '/images/user9.png', 'user9@example.com', 'pass1234', 12345),
('user10', 'User Ten', '/images/user10.png', 'user10@example.com', 'pass1234', 12345);

INSERT INTO `petfind`.`Post` (`title`, `description`, `imagesPath`, `fkIdUser`, `localization`, `publiType`, `animalName`, `animalSpecie`, `animalGender`, `animalColor`, `animalSize`, `datePosted`)
VALUES
('Lost Dog', 'Small brown dog lost in the park', 'https://storage.cloud.google.com/pet-find-dependencies/postImages/lostdog.jpg', 1, 'Park City', 'Lost', 'Buddy', 'Dog', 'Male', 'Brown', 'Small', '2024-06-07 14:00:00'),
('Found Cat', 'Found a black and white cat', 'https://storage.cloud.google.com/pet-find-dependencies/postImages/foundcatblackwhite.png', 2, 'Downtown', 'Found', 'Whiskers', 'Cat', 'Female', 'Black and White', 'Medium', '2024-06-07 15:00:00'),
('Missing Parrot', 'Green parrot missing near downtown area', 'https://storage.cloud.google.com/pet-find-dependencies/postImages/lostparrotgreen.jpg', 3, 'Downtown', 'Lost', 'Polly', 'Parrot', 'Male', 'Green', 'Small', '2024-06-08 09:00:00'),
('Found Dog', 'Golden retriever found near the river side', 'https://storage.cloud.google.com/pet-find-dependencies/postImages/goldenretrivier.jpg', 4, 'River Side', 'Found', 'Goldie', 'Dog', 'Female', 'Golden', 'Large', '2024-06-08 10:00:00'),
('Lost Cat', 'Grey cat lost last night', 'https://storage.cloud.google.com/pet-find-dependencies/postImages/greycat.jpg', 5, 'Suburbs', 'Lost', 'Shadow', 'Cat', 'Male', 'Grey', 'Medium', '2024-06-08 11:00:00'),
('Found Bird', 'Small bird found in the garden', 'https://storage.cloud.google.com/pet-find-dependencies/postImages/animais%5B1%5D.jpg', 6, 'Garden Area', 'Found', 'Tweety', 'Bird', 'Female', 'Yellow', 'Small', '2024-06-08 12:00:00'),
('Lost Dog', 'Black labrador missing', 'https://storage.cloud.google.com/pet-find-dependencies/postImages/animais%5B1%5D.jpg', 7, 'Park City', 'Lost', 'Blacky', 'Dog', 'Male', 'Black', 'Large', '2024-06-08 13:00:00'),
('Found Cat', 'White cat found sleeping in a barn', 'https://storage.cloud.google.com/pet-find-dependencies/postImages/animais%5B1%5D.jpg',7, 'Old Town', 'Found', 'Snowy', 'Cat', 'Female', 'White', 'Medium', '2024-06-08 14:00:00'),
('Lost Rabbit', 'White rabbit lost in the neighborhood', 'https://storage.cloud.google.com/pet-find-dependencies/postImages/animais%5B1%5D.jpg', 3, 'Hilltop', 'Lost', 'Bunny', 'Rabbit', 'Male', 'White', 'Small', '2024-06-08 15:00:00'),
('Found Dog', 'Husky with blue eyes found wandering streets', 'https://storage.cloud.google.com/pet-find-dependencies/postImages/animais%5B1%5D.jpg', 3, 'Downtown', 'Found', 'Sky', 'Dog', 'Male', 'Grey', 'Large', '2024-06-08 16:00:00');


INSERT INTO `petfind`.`Comments` (`text`, `fkIdPost`, `fkIdUser`)
VALUES
('Hope you find him!', 1, 2),
('I saw this dog yesterday!', 1, 3);
-- Adicione mais 8 comentários seguindo o padrão acima, alterando os valores conforme necessário

INSERT INTO `petfind`.`Reaction` (`fkIdUser`, `reactrionType`, `fkIdPost`)
VALUES
(1, 'Like', 1),
(2, 'Dislike', 1);
-- Adicione mais 8 reações seguindo o padrão acima, alterando os valores conforme necessário


-- Adicionando mais comentários
INSERT INTO `petfind`.`Comments` (`text`, `fkIdPost`, `fkIdUser`)
VALUES
('Is this parrot speaking?', 3, 4),
('I hope she finds a good home!', 4, 5),
('I think I saw him near the grocery store!', 5, 6),
('She looks so cute!', 6, 7),
('We are looking everywhere for him!', 7, 8),
('I can take her if no one claims her.', 8, 9),
('Please check the animal shelter!', 9, 10),
('He must be cold, poor thing!', 10, 1);

-- Adicionando mais reações
INSERT INTO `petfind`.`Reaction` (`fkIdUser`, `reactrionType`, `fkIdPost`)
VALUES
(3, 'Like', 3),
(4, 'Dislike', 4),
(5, 'Like', 5),
(6, 'Dislike', 6),
(7, 'Like', 7),
(8, 'Dislike', 8),
(9, 'Like', 9),
(10, 'Dislike', 10);