-- MySQL Script generated by MySQL Workbench
-- Wed May  8 20:16:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(25) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(8) NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Publicacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Publicacao` (
  `idPublicacao` INT NOT NULL AUTO_INCREMENT,
  `local` VARCHAR(999) NOT NULL,
  `especie` VARCHAR(45) NOT NULL,
  `cor` VARCHAR(45) NOT NULL,
  `raca` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `pelagem` VARCHAR(45) NULL,
  `porte` VARCHAR(45) NULL,
  `descricao` VARCHAR(999) NULL,
  `usuarioIdFK` INT NOT NULL,
  PRIMARY KEY (`idPublicacao`),
  UNIQUE INDEX `idPublicacao_UNIQUE` (`idPublicacao` ASC) VISIBLE,
  INDEX `usuarioIdFK_idx` (`usuarioIdFK` ASC) VISIBLE,
  CONSTRAINT `usuarioIdFK`
    FOREIGN KEY (`usuarioIdFK`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
